# Generated by Django 5.0.2 on 2024-02-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('jobSchedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY')], max_length=20)),
                ('time', models.TimeField()),
                ('starting_day', models.CharField(blank=True, choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], max_length=10, null=True)),
            ],
        ),
    ]
