# Generated by Django 5.0.2 on 2024-03-01 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_jobschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobschedule',
            name='starting_day',
        ),
        migrations.RemoveField(
            model_name='jobschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='jobschedule',
            name='starting',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
