# Generated by Django 5.0.2 on 2024-03-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_jobschedule_starting_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('yearly', 'YEARLY'), ('ONCE', 'ONCE')], max_length=20),
        ),
    ]
